// TotemBar - tools/preview_icons.js
// Offline preview renderer for the Rev 3 custom icon sheet
// (docs/superpowers/sdd/rev3-icons-brief.md): textures/icons.tga, generated by
// tools/gen_icons.js. Decodes the TGA, composites two rows of mock scenes, and
// writes tools/preview_icons.png so the art can be judged without the WoW
// client.
//
// Row 1 (brown bg): cells 1-6 raw at 90px each.
// Row 2 (dark bg): cells 1-4 composited UNDER the ring frame band (reads
//   textures/ring_round.tga's decorative frame cell, 1-indexed cell 64 / 0-based
//   index 63, and draws it over each glyph at a 48:36 ring:icon scale ratio -
//   the same compositing tools/preview_ring.js does), so empty-slot icons can
//   be judged in situ; then cell 7 (minimap glyph, transparent bg) at 40px and
//   20px (the two real minimap-button sizes).
//
// Zero dependencies: only Node's built-in "fs", "path", "zlib". Own PNG writer
// and TGA reader (does not import tools/preview_ring.js or
// tools/gen_ring_textures.js - both untouched, read-only reference for the
// compositing pattern). Run: node tools/preview_icons.js
"use strict";

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

// ---------------------------------------------------------------------
// Texture contract (must match tools/gen_icons.js / tools/gen_ring_textures.js)
// ---------------------------------------------------------------------
const ICONS_CELL = 128;   // px per grid cell in icons.tga
const ICONS_COLS = 4;     // icons.tga: 4x4 grid
const CELL_FIRE = 0, CELL_EARTH = 1, CELL_WATER = 2, CELL_AIR = 3;
const CELL_RECALL = 4, CELL_DROPSET = 5, CELL_MINIMAP = 6;

const RING_CELL = 64;     // px per grid cell in ring_round.tga
const RING_COLS = 8;      // ring_round.tga: 8x8 grid
const RING_FRAME_CELL = 63; // 0-based index of the decorative frame band (1-indexed cell 64)

// ---------------------------------------------------------------------
// Layout knobs (every magic number named)
// ---------------------------------------------------------------------
const ROW1_ICON_PX = 90;      // "raw at 90px each"
const ROW1_TILE_PAD = 12;
const ROW1_TILE_SIZE = ROW1_ICON_PX + ROW1_TILE_PAD * 2;

const RING_TO_ICON_RATIO = 48 / 36; // brief's "48/36 relative scale" (ring:icon)
const ROW2_ICON_PX = 90;
const ROW2_RING_PX = ROW2_ICON_PX * RING_TO_ICON_RATIO; // 120
const ROW2_TILE_PAD = 12;
const ROW2_TILE_SIZE = ROW2_RING_PX + ROW2_TILE_PAD * 2; // 144

const MINIMAP_PREVIEW_PX = [40, 20]; // "minimap sizes"

const BROWN_BG = [122, 84, 58];
const DARK_BG = [28, 26, 24];
const PAGE_BG = [16, 16, 16];
const MARGIN = 16;
const SECTION_GAP = 20;
const CAP_H = 18; // caption strip height under each tile
const ALPHA_FRINGE_CUTOFF = 1; // "zero out samples with alpha < 1/255" (i.e. < 1 of 255)

// ===========================================================================
// TGA reader (own copy - reads any 32bpp uncompressed truecolor TGA, handles
// both bottom-up and top-down descriptor bit)
// ===========================================================================
function readTGA(filePath) {
  const buf = fs.readFileSync(filePath);
  const idLength = buf[0];
  const imageType = buf[2];
  const width = buf[12] | (buf[13] << 8);
  const height = buf[14] | (buf[15] << 8);
  const bpp = buf[16];
  const descriptor = buf[17];
  if (imageType !== 2) throw new Error("preview_icons: expected uncompressed truecolor TGA (type 2), got " + imageType);
  if (bpp !== 32) throw new Error("preview_icons: expected 32bpp TGA, got " + bpp);

  const bytesPerPixel = bpp / 8;
  const rowBytes = width * bytesPerPixel;
  const dataStart = 18 + idLength;
  const topDown = (descriptor & 0x20) !== 0;

  const data = Buffer.alloc(width * height * 4);
  for (let r = 0; r < height; r++) {
    const rowOffset = dataStart + r * rowBytes;
    const destY = topDown ? r : (height - 1 - r);
    for (let x = 0; x < width; x++) {
      const so = rowOffset + x * bytesPerPixel;
      const b = buf[so], g = buf[so + 1], red = buf[so + 2], a = buf[so + 3];
      const doff = (destY * width + x) * 4;
      data[doff] = red; data[doff + 1] = g; data[doff + 2] = b; data[doff + 3] = a;
    }
  }
  return { width, height, data }; // top-down RGBA, straight alpha
}

// Extracts one cellSize x cellSize grid cell as a premultiplied-alpha
// Float64Array (avoids dark fringing under bilinear resampling).
function extractCellPremultiplied(image, cellIndex, cellSize, gridCols) {
  const col = cellIndex % gridCols;
  const row = Math.floor(cellIndex / gridCols);
  const out = new Float64Array(cellSize * cellSize * 4);
  for (let py = 0; py < cellSize; py++) {
    for (let px = 0; px < cellSize; px++) {
      const sx = col * cellSize + px;
      const sy = row * cellSize + py;
      const so = (sy * image.width + sx) * 4;
      const r = image.data[so], g = image.data[so + 1], b = image.data[so + 2], a = image.data[so + 3];
      const doff = (py * cellSize + px) * 4;
      const af = a / 255;
      out[doff] = r * af; out[doff + 1] = g * af; out[doff + 2] = b * af; out[doff + 3] = a;
    }
  }
  return out;
}

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }
function lerp(a, b, t) { return a + (b - a) * t; }

function bilinearSample(cellBuf, cellSize, sx, sy) {
  const x0f = Math.floor(sx), y0f = Math.floor(sy);
  const fx = sx - x0f, fy = sy - y0f;
  const x0 = clamp(x0f, 0, cellSize - 1), x1 = clamp(x0f + 1, 0, cellSize - 1);
  const y0 = clamp(y0f, 0, cellSize - 1), y1 = clamp(y0f + 1, 0, cellSize - 1);
  const i00 = (y0 * cellSize + x0) * 4, i10 = (y0 * cellSize + x1) * 4;
  const i01 = (y1 * cellSize + x0) * 4, i11 = (y1 * cellSize + x1) * 4;
  const out = new Array(4);
  for (let c = 0; c < 4; c++) {
    const top = lerp(cellBuf[i00 + c], cellBuf[i10 + c], fx);
    const bot = lerp(cellBuf[i01 + c], cellBuf[i11 + c], fx);
    out[c] = lerp(top, bot, fy);
  }
  return out; // premultiplied [pr, pg, pb, pa]
}

// Straight-alpha "over" compositing of a premultiplied sample onto an RGB
// canvas. Per the brief: samples with alpha < ALPHA_FRINGE_CUTOFF (out of
// 255) are zeroed first, to skip premultiply-fringe from the bilinear scale.
function compositeSample(canvas, idx, sample) {
  let a = sample[3]; // 0..255
  if (a < ALPHA_FRINGE_CUTOFF) a = 0; // brief: zero out samples with alpha < 1/255
  if (a <= 0) return;
  // Un-premultiply (sample[0..2] were stored as color*origAlpha/255) then
  // re-composite "over" the canvas at the (possibly cutoff-adjusted) alpha.
  const r = (sample[0] * 255) / a, g = (sample[1] * 255) / a, b = (sample[2] * 255) / a;
  const aNorm = a / 255, inv = 1 - aNorm;
  canvas[idx] = r * aNorm + canvas[idx] * inv;
  canvas[idx + 1] = g * aNorm + canvas[idx + 1] * inv;
  canvas[idx + 2] = b * aNorm + canvas[idx + 2] * inv;
}

// Composites a texture cell, scaled to layerSize px and centered at (cx,cy).
function compositeLayerCentered(canvas, canvasSize, cellBuf, cellSize, cx, cy, layerSize) {
  const half = layerSize / 2;
  const left = cx - half, top = cy - half;
  const x0 = Math.max(0, Math.floor(left));
  const x1 = Math.min(canvasSize - 1, Math.ceil(left + layerSize) - 1);
  const y0 = Math.max(0, Math.floor(top));
  const y1 = Math.min(canvasSize - 1, Math.ceil(top + layerSize) - 1);
  for (let y = y0; y <= y1; y++) {
    const v = (y + 0.5 - top) / layerSize;
    if (v < 0 || v >= 1) continue;
    const sy = v * cellSize - 0.5;
    for (let x = x0; x <= x1; x++) {
      const u = (x + 0.5 - left) / layerSize;
      if (u < 0 || u >= 1) continue;
      const sx = u * cellSize - 0.5;
      const sample = bilinearSample(cellBuf, cellSize, sx, sy);
      compositeSample(canvas, (y * canvasSize + x) * 3, sample);
    }
  }
}

// ===========================================================================
// Tile / page assembly
// ===========================================================================
function fillCanvas(canvas, size, bg) {
  for (let i = 0; i < size * size; i++) {
    canvas[i * 3] = bg[0]; canvas[i * 3 + 1] = bg[1]; canvas[i * 3 + 2] = bg[2];
  }
}

function blit(outBuf, outW, outH, srcCanvas, srcSize, dx, dy) {
  for (let y = 0; y < srcSize; y++) {
    const oy = dy + y;
    if (oy < 0 || oy >= outH) continue;
    for (let x = 0; x < srcSize; x++) {
      const ox = dx + x;
      if (ox < 0 || ox >= outW) continue;
      const si = (y * srcSize + x) * 3;
      const oi = (oy * outW + ox) * 3;
      outBuf[oi] = Math.round(clamp(srcCanvas[si], 0, 255));
      outBuf[oi + 1] = Math.round(clamp(srcCanvas[si + 1], 0, 255));
      outBuf[oi + 2] = Math.round(clamp(srcCanvas[si + 2], 0, 255));
    }
  }
}

function fillRect(outBuf, outW, x0, y0, w, h, color) {
  for (let y = y0; y < y0 + h; y++) {
    for (let x = x0; x < x0 + w; x++) {
      const idx = (y * outW + x) * 3;
      outBuf[idx] = color[0]; outBuf[idx + 1] = color[1]; outBuf[idx + 2] = color[2];
    }
  }
}

// Tiny 5x7 bitmap digit font for tile captions (same minimal glyph set used
// by tools/preview_ring.js, reimplemented here).
const DIGITS = {
  "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
  "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
  "3": ["11111", "00010", "00100", "00010", "00001", "10001", "01110"],
  "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
  "5": ["11111", "10000", "11110", "00001", "00001", "10001", "01110"],
  "6": ["00110", "01000", "10000", "11110", "10001", "10001", "01110"],
  "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
  "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
};
function drawDigitString(outBuf, outW, outH, x, y, text, color, scale) {
  let cursorX = x;
  for (let i = 0; i < text.length; i++) {
    const glyph = DIGITS[text[i]];
    if (glyph) {
      for (let gy = 0; gy < 7; gy++) {
        const row = glyph[gy];
        for (let gx = 0; gx < 5; gx++) {
          if (row[gx] === "1") {
            for (let py = 0; py < scale; py++) {
              for (let px = 0; px < scale; px++) {
                const ox = cursorX + gx * scale + px, oy = y + gy * scale + py;
                if (ox < 0 || ox >= outW || oy < 0 || oy >= outH) continue;
                const idx = (oy * outW + ox) * 3;
                outBuf[idx] = color[0]; outBuf[idx + 1] = color[1]; outBuf[idx + 2] = color[2];
              }
            }
          }
        }
      }
    }
    cursorX += (5 + 1) * scale;
  }
}

// ===========================================================================
// Minimal zero-dependency PNG writer (IHDR + IDAT + IEND, RGB8, filter 0)
// ===========================================================================
const CRC_TABLE = (function () {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    table[n] = c >>> 0;
  }
  return table;
})();
function crc32(buf) {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
  return (c ^ 0xFFFFFFFF) >>> 0;
}
function pngChunk(type, data) {
  const typeBuf = Buffer.from(type, "ascii");
  const lenBuf = Buffer.alloc(4); lenBuf.writeUInt32BE(data.length, 0);
  const crcBuf = Buffer.alloc(4); crcBuf.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([lenBuf, typeBuf, data, crcBuf]);
}
function encodePNG_RGB8(width, height, rgbBuffer) {
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0); ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; ihdr[9] = 2; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;
  const rowBytes = width * 3;
  const raw = Buffer.alloc((rowBytes + 1) * height);
  for (let y = 0; y < height; y++) {
    const rowStart = y * (rowBytes + 1);
    raw[rowStart] = 0;
    rgbBuffer.copy(raw, rowStart + 1, y * rowBytes, (y + 1) * rowBytes);
  }
  const idatData = zlib.deflateSync(raw);
  return Buffer.concat([sig, pngChunk("IHDR", ihdr), pngChunk("IDAT", idatData), pngChunk("IEND", Buffer.alloc(0))]);
}

// ===========================================================================
// Main
// ===========================================================================
function main() {
  const iconsPath = path.join(__dirname, "..", "textures", "icons.tga");
  const ringPath = path.join(__dirname, "..", "textures", "ring_round.tga");
  const iconsImage = readTGA(iconsPath);
  const ringImage = readTGA(ringPath);

  const iconCache = {};
  function iconCell(idx) {
    if (!iconCache[idx]) iconCache[idx] = extractCellPremultiplied(iconsImage, idx, ICONS_CELL, ICONS_COLS);
    return iconCache[idx];
  }
  const frameCellBuf = extractCellPremultiplied(ringImage, RING_FRAME_CELL, RING_CELL, RING_COLS);

  // ---- Row 1: cells 1-6 raw at 90px on brown bg ----
  const row1Cells = [CELL_FIRE, CELL_EARTH, CELL_WATER, CELL_AIR, CELL_RECALL, CELL_DROPSET];
  const row1Cols = row1Cells.length;
  const row1TileH = ROW1_TILE_SIZE + CAP_H;
  const row1GridW = row1Cols * ROW1_TILE_SIZE + (row1Cols + 1) * ROW1_TILE_PAD;
  const row1GridH = row1TileH + 2 * ROW1_TILE_PAD;

  // ---- Row 2: cells 1-4 under ring frame (90px icon / 120px ring), then
  // minimap glyph at 40px and 20px - 6 tiles total, dark bg ----
  const row2Cells = [CELL_FIRE, CELL_EARTH, CELL_WATER, CELL_AIR];
  const row2Cols = row2Cells.length + MINIMAP_PREVIEW_PX.length;
  const row2TileH = ROW2_TILE_SIZE + CAP_H;
  const row2GridW = row2Cols * ROW2_TILE_SIZE + (row2Cols + 1) * ROW2_TILE_PAD;
  const row2GridH = row2TileH + 2 * ROW2_TILE_PAD;

  const contentW = Math.max(row1GridW, row2GridW);
  const outW = contentW + 2 * MARGIN;
  const outH = MARGIN + row1GridH + SECTION_GAP + row2GridH + MARGIN;

  const outBuf = Buffer.alloc(outW * outH * 3);
  for (let i = 0; i < outW * outH; i++) {
    outBuf[i * 3] = PAGE_BG[0]; outBuf[i * 3 + 1] = PAGE_BG[1]; outBuf[i * 3 + 2] = PAGE_BG[2];
  }

  // --- Row 1 ---
  const row1GridX = MARGIN + Math.floor((contentW - row1GridW) / 2);
  const row1GridY = MARGIN;
  fillRect(outBuf, outW, row1GridX, row1GridY, row1GridW, row1GridH, BROWN_BG);
  for (let i = 0; i < row1Cells.length; i++) {
    const tileX = row1GridX + ROW1_TILE_PAD + i * (ROW1_TILE_SIZE + ROW1_TILE_PAD);
    const tileY = row1GridY + ROW1_TILE_PAD;
    const canvas = new Float64Array(ROW1_TILE_SIZE * ROW1_TILE_SIZE * 3);
    fillCanvas(canvas, ROW1_TILE_SIZE, BROWN_BG);
    const cx = ROW1_TILE_SIZE / 2, cy = ROW1_TILE_SIZE / 2;
    compositeLayerCentered(canvas, ROW1_TILE_SIZE, iconCell(row1Cells[i]), ICONS_CELL, cx, cy, ROW1_ICON_PX);
    blit(outBuf, outW, outH, canvas, ROW1_TILE_SIZE, tileX, tileY);
    const caption = String(row1Cells[i] + 1);
    const capY = tileY + ROW1_TILE_SIZE + Math.floor((CAP_H - 7 * 2) / 2);
    const capX = tileX + Math.floor((ROW1_TILE_SIZE - (caption.length * 6 * 2 - 2)) / 2);
    drawDigitString(outBuf, outW, outH, capX, capY, caption, [255, 255, 255], 2);
  }

  // --- Row 2 ---
  const row2GridX = MARGIN + Math.floor((contentW - row2GridW) / 2);
  const row2GridY = row1GridY + row1GridH + SECTION_GAP;
  fillRect(outBuf, outW, row2GridX, row2GridY, row2GridW, row2GridH, DARK_BG);

  function row2TileOrigin(i) {
    return {
      x: row2GridX + ROW2_TILE_PAD + i * (ROW2_TILE_SIZE + ROW2_TILE_PAD),
      y: row2GridY + ROW2_TILE_PAD,
    };
  }

  for (let i = 0; i < row2Cells.length; i++) {
    const { x: tileX, y: tileY } = row2TileOrigin(i);
    const canvas = new Float64Array(ROW2_TILE_SIZE * ROW2_TILE_SIZE * 3);
    fillCanvas(canvas, ROW2_TILE_SIZE, DARK_BG);
    const cx = ROW2_TILE_SIZE / 2, cy = ROW2_TILE_SIZE / 2;
    // draw order: icon underneath, frame band over it (covers the icon's
    // opaque square corners) - same z-order tools/preview_ring.js uses.
    compositeLayerCentered(canvas, ROW2_TILE_SIZE, iconCell(row2Cells[i]), ICONS_CELL, cx, cy, ROW2_ICON_PX);
    compositeLayerCentered(canvas, ROW2_TILE_SIZE, frameCellBuf, RING_CELL, cx, cy, ROW2_RING_PX);
    blit(outBuf, outW, outH, canvas, ROW2_TILE_SIZE, tileX, tileY);
    const caption = String(row2Cells[i] + 1);
    const capY = tileY + ROW2_TILE_SIZE + Math.floor((CAP_H - 7 * 2) / 2);
    const capX = tileX + Math.floor((ROW2_TILE_SIZE - (caption.length * 6 * 2 - 2)) / 2);
    drawDigitString(outBuf, outW, outH, capX, capY, caption, [255, 255, 255], 2);
  }
  for (let m = 0; m < MINIMAP_PREVIEW_PX.length; m++) {
    const i = row2Cells.length + m;
    const { x: tileX, y: tileY } = row2TileOrigin(i);
    const canvas = new Float64Array(ROW2_TILE_SIZE * ROW2_TILE_SIZE * 3);
    fillCanvas(canvas, ROW2_TILE_SIZE, DARK_BG);
    const cx = ROW2_TILE_SIZE / 2, cy = ROW2_TILE_SIZE / 2;
    compositeLayerCentered(canvas, ROW2_TILE_SIZE, iconCell(CELL_MINIMAP), ICONS_CELL, cx, cy, MINIMAP_PREVIEW_PX[m]);
    blit(outBuf, outW, outH, canvas, ROW2_TILE_SIZE, tileX, tileY);
    const caption = "7";
    const capY = tileY + ROW2_TILE_SIZE + Math.floor((CAP_H - 7 * 2) / 2);
    const capX = tileX + Math.floor((ROW2_TILE_SIZE - (caption.length * 6 * 2 - 2)) / 2);
    drawDigitString(outBuf, outW, outH, capX, capY, caption, [255, 255, 255], 2);
  }

  const png = encodePNG_RGB8(outW, outH, outBuf);
  const outPath = path.join(__dirname, "preview_icons.png");
  fs.writeFileSync(outPath, png);
  console.log("wrote " + outPath + " (" + png.length + " bytes, " + outW + "x" + outH + ")");
}

main();
