// TotemBar - tools/preview_ui.js
// Offline preview renderer for the Rev 4 UI-chrome textures
// (.superpowers/sdd/rev4-ui-brief.md): textures/panel_border.tga (edgeFile
// strip, generated by tools/gen_ui_textures.js), textures/panel_bg.tga
// (tileable interior background), and textures/ui.tga (shadow plate / emblem
// / divider). Also reuses textures/ring_round.tga (frame + arc cells) and
// textures/icons.tga (element glyphs) for the bar-strip mock scene.
//
// The whole point of this file is to composite the border EXACTLY like the
// WoW client's SetBackdrop(edgeFile=...) does: 4 corner quads placed
// unrotated, L/R edges tiled vertically as stored, and T/B edges tiled
// horizontally AFTER a 90-degree CLOCKWISE rotation of the stored (vertical-
// strip) cell - see rotateCW90Premult() below. Getting this rotation
// direction/mapping wrong is exactly the "striped garbage" failure mode the
// brief warns about.
//
// Zero dependencies: only Node's built-in "fs", "path", "zlib". Own TGA
// reader/PNG writer (does not import tools/preview_ring.js or
// tools/preview_icons.js - both untouched, read-only reference for the
// compositing pattern, same reimplementation approach those two already use
// relative to each other). Run: node tools/preview_ui.js
"use strict";

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }
function lerp(a, b, t) { return a + (b - a) * t; }

// ===========================================================================
// TGA reader (own copy, same contract as the sibling preview scripts)
// ===========================================================================
function readTGA(filePath) {
  const buf = fs.readFileSync(filePath);
  const idLength = buf[0];
  const imageType = buf[2];
  const width = buf[12] | (buf[13] << 8);
  const height = buf[14] | (buf[15] << 8);
  const bpp = buf[16];
  const descriptor = buf[17];
  if (imageType !== 2) throw new Error("preview_ui: expected uncompressed truecolor TGA (type 2), got " + imageType);
  if (bpp !== 32) throw new Error("preview_ui: expected 32bpp TGA, got " + bpp);

  const bytesPerPixel = bpp / 8;
  const rowBytes = width * bytesPerPixel;
  const dataStart = 18 + idLength;
  const topDown = (descriptor & 0x20) !== 0;

  const data = Buffer.alloc(width * height * 4);
  for (let r = 0; r < height; r++) {
    const rowOffset = dataStart + r * rowBytes;
    const destY = topDown ? r : (height - 1 - r);
    for (let x = 0; x < width; x++) {
      const so = rowOffset + x * bytesPerPixel;
      const b = buf[so], g = buf[so + 1], red = buf[so + 2], a = buf[so + 3];
      const doff = (destY * width + x) * 4;
      data[doff] = red; data[doff + 1] = g; data[doff + 2] = b; data[doff + 3] = a;
    }
  }
  return { width, height, data }; // top-down straight-alpha RGBA
}

// Extracts one cellSize x cellSize grid cell as a premultiplied-alpha
// Float64Array [pr,pg,pb,a] (a stored as plain 0..255, not premultiplied -
// same convention tools/gen_ring_textures.js's sibling preview scripts use).
function extractCellPremultiplied(image, cellIndex, cellSize, gridCols) {
  const col = cellIndex % gridCols;
  const row = Math.floor(cellIndex / gridCols);
  const out = new Float64Array(cellSize * cellSize * 4);
  for (let py = 0; py < cellSize; py++) {
    for (let px = 0; px < cellSize; px++) {
      const sx = col * cellSize + px;
      const sy = row * cellSize + py;
      const so = (sy * image.width + sx) * 4;
      const r = image.data[so], g = image.data[so + 1], b = image.data[so + 2], a = image.data[so + 3];
      const doff = (py * cellSize + px) * 4;
      const af = a / 255;
      out[doff] = r * af; out[doff + 1] = g * af; out[doff + 2] = b * af; out[doff + 3] = a;
    }
  }
  return out;
}

// Rotates a cellSize x cellSize premultiplied buffer 90 degrees CLOCKWISE:
// dest(x,y) = source(y, cellSize-1-x). Derived from the standard CW matrix-
// rotation mapping result[i][j] = source[H-1-j][i] (row=i,col=j) rewritten in
// (x,y) terms: source_x = result_y, source_y = H-1-result_x. This is the
// exact operation the WoW client performs on the T/B edgeFile cells at
// render time (per the brief's CRITICAL orientation facts) - applying it
// here in the offline compositor is what makes this preview trustworthy
// instead of just re-displaying the raw (unrotated) file content.
function rotateCW90Premult(buf, size) {
  const out = new Float64Array(size * size * 4);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const sx = y, sy = size - 1 - x;
      const so = (sy * size + sx) * 4, doff = (y * size + x) * 4;
      out[doff] = buf[so]; out[doff + 1] = buf[so + 1]; out[doff + 2] = buf[so + 2]; out[doff + 3] = buf[so + 3];
    }
  }
  return out;
}

function bilinearSample(cellBuf, cellSize, sx, sy) {
  const x0f = Math.floor(sx), y0f = Math.floor(sy);
  const fx = sx - x0f, fy = sy - y0f;
  const x0 = clamp(x0f, 0, cellSize - 1), x1 = clamp(x0f + 1, 0, cellSize - 1);
  const y0 = clamp(y0f, 0, cellSize - 1), y1 = clamp(y0f + 1, 0, cellSize - 1);
  const i00 = (y0 * cellSize + x0) * 4, i10 = (y0 * cellSize + x1) * 4;
  const i01 = (y1 * cellSize + x0) * 4, i11 = (y1 * cellSize + x1) * 4;
  const out = new Array(4);
  for (let c = 0; c < 4; c++) {
    const top = lerp(cellBuf[i00 + c], cellBuf[i10 + c], fx);
    const bot = lerp(cellBuf[i01 + c], cellBuf[i11 + c], fx);
    out[c] = lerp(top, bot, fy);
  }
  return out; // premultiplied [pr,pg,pb,a(0..255)]
}

// Straight-alpha "over" compositing of a premultiplied sample onto an RGB
// canvas. Fringe guard: alpha < 1/255 contributes nothing (skips bilinear
// premultiply noise at near-zero alpha, same rule the sibling scripts use).
function compositeSample(canvas, idx, sample) {
  const a = sample[3];
  if (a < 1) return;
  const r = (sample[0] * 255) / a, g = (sample[1] * 255) / a, b = (sample[2] * 255) / a;
  const aNorm = a / 255, inv = 1 - aNorm;
  canvas[idx] = r * aNorm + canvas[idx] * inv;
  canvas[idx + 1] = g * aNorm + canvas[idx + 1] * inv;
  canvas[idx + 2] = b * aNorm + canvas[idx + 2] * inv;
}

// Composites a texture cell, scaled to (layerW x layerH) px and centered at
// (cx,cy) - independent width/height scale (needed for the stretched shadow
// plate ellipse).
function compositeLayerScaled(canvas, canvasSize, cellBuf, cellSize, cx, cy, layerW, layerH) {
  const halfW = layerW / 2, halfH = layerH / 2;
  const left = cx - halfW, top = cy - halfH;
  const x0 = Math.max(0, Math.floor(left));
  const x1 = Math.min(canvasSize - 1, Math.ceil(left + layerW) - 1);
  const y0 = Math.max(0, Math.floor(top));
  const y1 = Math.min(canvasSize - 1, Math.ceil(top + layerH) - 1);
  for (let y = y0; y <= y1; y++) {
    const v = (y + 0.5 - top) / layerH;
    if (v < 0 || v >= 1) continue;
    const sy = v * cellSize - 0.5;
    for (let x = x0; x <= x1; x++) {
      const u = (x + 0.5 - left) / layerW;
      if (u < 0 || u >= 1) continue;
      const sx = u * cellSize - 0.5;
      const sample = bilinearSample(cellBuf, cellSize, sx, sy);
      compositeSample(canvas, (y * canvasSize + x) * 3, sample);
    }
  }
}
function compositeLayerCentered(canvas, canvasSize, cellBuf, cellSize, cx, cy, layerSize) {
  compositeLayerScaled(canvas, canvasSize, cellBuf, cellSize, cx, cy, layerSize, layerSize);
}

// ===========================================================================
// 9-slice border compositing (the CRITICAL part)
// ===========================================================================
const CS = 16; // corner/edge cell size (edgeSize)

// Given LOCAL panel coordinates (lx,ly) within a w x h panel, returns the
// premultiplied [pr,pg,pb,a] sample from the correct 9-slice piece, or null
// if (lx,ly) is in the open interior (caller should draw the tiled bg there).
// cells = { L, R, T, B, TL, TR, BL, BR } - T and B must already be the
// ROTATED (rotateCW90Premult) buffers; L/R/corners are used as-authored.
function sampleBorderAt(cells, lx, ly, w, h) {
  const inTop = ly < CS, inBottom = ly >= h - CS, inLeft = lx < CS, inRight = lx >= w - CS;
  let buf, cx, cy;
  if (inTop && inLeft) { buf = cells.TL; cx = lx; cy = ly; }
  else if (inTop && inRight) { buf = cells.TR; cx = lx - (w - CS); cy = ly; }
  else if (inBottom && inLeft) { buf = cells.BL; cx = lx; cy = ly - (h - CS); }
  else if (inBottom && inRight) { buf = cells.BR; cx = lx - (w - CS); cy = ly - (h - CS); }
  else if (inTop) { buf = cells.T; cx = (lx - CS) % CS; cy = ly; }
  else if (inBottom) { buf = cells.B; cx = (lx - CS) % CS; cy = ly - (h - CS); }
  else if (inLeft) { buf = cells.L; cx = lx; cy = (ly - CS) % CS; }
  else if (inRight) { buf = cells.R; cx = lx - (w - CS); cy = (ly - CS) % CS; }
  else return null;
  const o = (cy * CS + cx) * 4;
  return [buf[o], buf[o + 1], buf[o + 2], buf[o + 3]];
}

// Draws a full 9-sliced panel at (px,py) sized w x h: tiled bg.tga (straight
// RGBA, opaque) inside an `inset`-px margin (drawn FIRST, so the border's
// transparent rounded-corner cutaways and faded inner edge reveal it),
// border on top (drawn SECOND).
function drawPanel(canvas, size, px, py, w, h, cells, bgData, bgSize, inset) {
  for (let ly = 0; ly < h; ly++) {
    const cy = py + ly;
    if (cy < 0 || cy >= size) continue;
    for (let lx = 0; lx < w; lx++) {
      const cx = px + lx;
      if (cx < 0 || cx >= size) continue;
      const idx = (cy * size + cx) * 3;
      if (lx >= inset && lx < w - inset && ly >= inset && ly < h - inset) {
        const tx = ((lx - inset) % bgSize + bgSize) % bgSize;
        const ty = ((ly - inset) % bgSize + bgSize) % bgSize;
        const so = (ty * bgSize + tx) * 4;
        canvas[idx] = bgData[so]; canvas[idx + 1] = bgData[so + 1]; canvas[idx + 2] = bgData[so + 2];
      }
      const sample = sampleBorderAt(cells, lx, ly, w, h);
      if (sample) compositeSample(canvas, idx, sample);
    }
  }
}

// ===========================================================================
// Tiny 5x7 bitmap fonts (digits reused for captions; caps letters for the
// "TotemBar" title bar - own copies, independent of the sibling scripts'
// digit-only tables).
// ===========================================================================
const DIGITS = {
  "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
  "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
  "3": ["11111", "00010", "00100", "00010", "00001", "10001", "01110"],
};
const LETTERS = {
  T: ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
  O: ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
  E: ["11111", "10000", "11110", "10000", "10000", "10000", "11111"],
  M: ["10001", "11011", "10101", "10101", "10001", "10001", "10001"],
  B: ["11110", "10001", "10001", "11110", "10001", "10001", "11110"],
  A: ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
  R: ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
};
function drawGlyphString(outBuf, outW, outH, table, x, y, text, color, scale) {
  let cursorX = x;
  for (let i = 0; i < text.length; i++) {
    const glyph = table[text[i]];
    if (glyph) {
      for (let gy = 0; gy < 7; gy++) {
        const row = glyph[gy];
        for (let gx = 0; gx < 5; gx++) {
          if (row[gx] === "1") {
            for (let py = 0; py < scale; py++) {
              for (let px = 0; px < scale; px++) {
                const ox = cursorX + gx * scale + px, oy = y + gy * scale + py;
                if (ox < 0 || ox >= outW || oy < 0 || oy >= outH) continue;
                const idx = (oy * outW + ox) * 3;
                outBuf[idx] = color[0]; outBuf[idx + 1] = color[1]; outBuf[idx + 2] = color[2];
              }
            }
          }
        }
      }
    }
    cursorX += (5 + 1) * scale;
  }
  return cursorX - scale;
}

function fillCanvas(canvas, w, h, bg) {
  for (let i = 0; i < w * h; i++) { canvas[i * 3] = bg[0]; canvas[i * 3 + 1] = bg[1]; canvas[i * 3 + 2] = bg[2]; }
}
function fillRect(canvas, w, x0, y0, rw, rh, color) {
  for (let y = y0; y < y0 + rh; y++) for (let x = x0; x < x0 + rw; x++) { const idx = (y * w + x) * 3; canvas[idx] = color[0]; canvas[idx + 1] = color[1]; canvas[idx + 2] = color[2]; }
}
function strokeRect(canvas, w, x0, y0, rw, rh, color) {
  fillRect(canvas, w, x0, y0, rw, 1, color);
  fillRect(canvas, w, x0, y0 + rh - 1, rw, 1, color);
  fillRect(canvas, w, x0, y0, 1, rh, color);
  fillRect(canvas, w, x0 + rw - 1, y0, 1, rh, color);
}
function blit(outBuf, outW, outH, srcCanvas, srcW, srcH, dx, dy) {
  for (let y = 0; y < srcH; y++) {
    const oy = dy + y;
    if (oy < 0 || oy >= outH) continue;
    for (let x = 0; x < srcW; x++) {
      const ox = dx + x;
      if (ox < 0 || ox >= outW) continue;
      const si = (y * srcW + x) * 3, oi = (oy * outW + ox) * 3;
      outBuf[oi] = Math.round(clamp(srcCanvas[si], 0, 255));
      outBuf[oi + 1] = Math.round(clamp(srcCanvas[si + 1], 0, 255));
      outBuf[oi + 2] = Math.round(clamp(srcCanvas[si + 2], 0, 255));
    }
  }
}

// ===========================================================================
// Minimal zero-dependency PNG writer (IHDR + IDAT + IEND, RGB8, filter 0)
// ===========================================================================
const CRC_TABLE = (function () {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1); table[n] = c >>> 0; }
  return table;
})();
function crc32(buf) { let c = 0xFFFFFFFF; for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8); return (c ^ 0xFFFFFFFF) >>> 0; }
function pngChunk(type, data) {
  const typeBuf = Buffer.from(type, "ascii");
  const lenBuf = Buffer.alloc(4); lenBuf.writeUInt32BE(data.length, 0);
  const crcBuf = Buffer.alloc(4); crcBuf.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([lenBuf, typeBuf, data, crcBuf]);
}
function encodePNG_RGB8(width, height, rgbBuffer) {
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0); ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; ihdr[9] = 2; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;
  const rowBytes = width * 3;
  const raw = Buffer.alloc((rowBytes + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (rowBytes + 1)] = 0;
    rgbBuffer.copy(raw, y * (rowBytes + 1) + 1, y * rowBytes, (y + 1) * rowBytes);
  }
  const idatData = zlib.deflateSync(raw);
  return Buffer.concat([sig, pngChunk("IHDR", ihdr), pngChunk("IDAT", idatData), pngChunk("IEND", Buffer.alloc(0))]);
}

// ===========================================================================
// Scene builders
// ===========================================================================
const PANEL_W = 300, PANEL_H = 360;
const PANEL_INSET = 5;
const BAR_SLOT_W = 150, BAR_SLOTS = 4;
const BAR_W = BAR_SLOT_W * BAR_SLOTS, BAR_H = 170;
const RING_FRAME_SIZE = 96, RING_ICON_SIZE = 72; // 48:36 ratio kept (96=48*2, 72=36*2)
const SHADOW_W = 55, SHADOW_H = 24, SHADOW_OFFSET_Y = 10;
const RAW2X_CELL = 128, RAW2X_SCALE = 2, RAW2X_SIZE = RAW2X_CELL * RAW2X_SCALE; // 256

function buildScenePanel(bg, cells, bgTgaData, bgTgaSize, uiCells) {
  const canvas = new Float64Array(PANEL_W * PANEL_H * 3);
  fillCanvas(canvas, PANEL_W, PANEL_H, bg);
  drawPanel(canvas, PANEL_W, 0, 0, PANEL_W, PANEL_H, cells, bgTgaData, bgTgaSize, PANEL_INSET);

  // Emblem, top-left, 44px, just inside the border+inset.
  const emblemX = CS + PANEL_INSET + 22 + 6, emblemY = CS + PANEL_INSET + 22 + 4;
  compositeLayerCentered(canvas, PANEL_W, uiCells.emblem, 128, emblemX, emblemY, 44);

  // Gold title, vertically centered with the emblem.
  const GOLD = [230, 190, 110];
  drawGlyphString(canvas, PANEL_W, PANEL_H, LETTERS, emblemX + 30, emblemY - 7, "TOTEMBAR", GOLD, 2);

  // Two divider lines (stretched to interior width x 7px), + 3 fake content rows.
  const contentLeft = CS + PANEL_INSET + 4, contentRight = PANEL_W - CS - PANEL_INSET - 4;
  const dividerW = contentRight - contentLeft;
  const divY1 = emblemY + 30, divY2 = divY1 + 90;
  compositeLayerScaled(canvas, PANEL_W, uiCells.divider, 128, contentLeft + dividerW / 2, divY1, dividerW, 7);
  compositeLayerScaled(canvas, PANEL_W, uiCells.divider, 128, contentLeft + dividerW / 2, divY2, dividerW, 7);

  const rowColor = [200, 200, 200];
  for (let i = 0; i < 3; i++) {
    const ry = divY1 + 20 + i * 22;
    strokeRect(canvas, PANEL_W, contentLeft, ry, 14, 14, rowColor);
    fillRect(canvas, PANEL_W, contentLeft + 24, ry + 10, 90, 2, [90, 88, 84]); // fake label bar
  }
  return { canvas, w: PANEL_W, h: PANEL_H, caption: "1" };
}

function buildSceneBarStrip(bg, ringFrameBuf, arcFullBuf, iconCells, uiCells) {
  const canvas = new Float64Array(BAR_W * BAR_H * 3);
  fillCanvas(canvas, BAR_W, BAR_H, bg);
  const tints = [[1.0, 0.45, 0.10], [0.40, 0.85, 0.30], [0.25, 0.60, 1.00], [0.70, 0.55, 1.00]]; // Fire/Earth/Water/Air
  const iconIdx = [0, 1, 2, 3]; // FIRE,EARTH,WATER,AIR (0-based, matches tools/gen_icons.js)
  for (let i = 0; i < BAR_SLOTS; i++) {
    const cx = BAR_SLOT_W * i + BAR_SLOT_W / 2, cy = BAR_H / 2 - 8;
    // shadow plate first (under everything), stretched, offset below center
    compositeLayerScaled(canvas, BAR_W, uiCells.shadow, 128, cx, cy + SHADOW_OFFSET_Y + RING_FRAME_SIZE / 2, SHADOW_W, SHADOW_H);
    // icon, frame band over it, tinted arc frame over that (mirrors ui.lua's z-order)
    compositeLayerCentered(canvas, BAR_W, iconCells[iconIdx[i]], 128, cx, cy, RING_ICON_SIZE);
    compositeLayerCentered(canvas, BAR_W, ringFrameBuf, 64, cx, cy, RING_FRAME_SIZE);
    // tinted arc frame ("+ an arc frame"): recolor the white-source arc cell via a tint pass
    const tinted = new Float64Array(64 * 64 * 4);
    for (let p = 0; p < 64 * 64; p++) {
      const a = arcFullBuf[p * 4 + 3];
      tinted[p * 4] = tints[i][0] * a; tinted[p * 4 + 1] = tints[i][1] * a; tinted[p * 4 + 2] = tints[i][2] * a; tinted[p * 4 + 3] = a;
    }
    compositeLayerCentered(canvas, BAR_W, tinted, 64, cx, cy, RING_FRAME_SIZE);
  }
  return { canvas, w: BAR_W, h: BAR_H, caption: "2" };
}

function buildSceneRaw2x(bg, uiCells) {
  const w = RAW2X_SIZE * 2 + 24, h = RAW2X_SIZE;
  const canvas = new Float64Array(w * h * 3);
  fillCanvas(canvas, w, h, bg);
  compositeLayerScaled(canvas, w, uiCells.divider, 128, RAW2X_SIZE / 2, h / 2, RAW2X_SIZE, RAW2X_SIZE);
  compositeLayerScaled(canvas, w, uiCells.emblem, 128, RAW2X_SIZE + 24 + RAW2X_SIZE / 2, h / 2, RAW2X_SIZE, RAW2X_SIZE);
  return { canvas, w, h, caption: "3" };
}

// ===========================================================================
// Main
// ===========================================================================
function main() {
  const texDir = path.join(__dirname, "..", "textures");
  const borderImg = readTGA(path.join(texDir, "panel_border.tga"));
  const bgImg = readTGA(path.join(texDir, "panel_bg.tga"));
  const uiImg = readTGA(path.join(texDir, "ui.tga"));
  const ringImg = readTGA(path.join(texDir, "ring_round.tga"));
  const iconsImg = readTGA(path.join(texDir, "icons.tga"));

  // Border cells (128x16, 8 cols x 1 row, cellSize=16); T/B rotated CW here.
  const L = extractCellPremultiplied(borderImg, 0, CS, 8);
  const R = extractCellPremultiplied(borderImg, 1, CS, 8);
  const Traw = extractCellPremultiplied(borderImg, 2, CS, 8);
  const Braw = extractCellPremultiplied(borderImg, 3, CS, 8);
  const TL = extractCellPremultiplied(borderImg, 4, CS, 8);
  const TR = extractCellPremultiplied(borderImg, 5, CS, 8);
  const BL = extractCellPremultiplied(borderImg, 6, CS, 8);
  const BR = extractCellPremultiplied(borderImg, 7, CS, 8);
  const cells = { L, R, T: rotateCW90Premult(Traw, CS), B: rotateCW90Premult(Braw, CS), TL, TR, BL, BR };

  const bgTgaData = bgImg.data; // 128x128, opaque, straight = premultiplied (alpha 255)
  const bgTgaSize = bgImg.width;

  const uiCells = {
    shadow: extractCellPremultiplied(uiImg, 0, 128, 2),
    emblem: extractCellPremultiplied(uiImg, 1, 128, 2),
    divider: extractCellPremultiplied(uiImg, 2, 128, 2),
  };

  const RING_FRAME_CELL = 63; // 0-based index of ring_round.tga's decorative frame band (1-indexed cell 64)
  const RING_ARC_FULL = 61;   // 0-based index of the full duration arc (f=61/61=1.0)
  const ringFrameBuf = extractCellPremultiplied(ringImg, RING_FRAME_CELL, 64, 8);
  const arcFullBuf = extractCellPremultiplied(ringImg, RING_ARC_FULL, 64, 8);
  const iconCells = [0, 1, 2, 3].map((i) => extractCellPremultiplied(iconsImg, i, 128, 4)); // FIRE,EARTH,WATER,AIR

  const BROWN_BG = [122, 84, 58];
  const DARK_BG = [28, 26, 24];
  const PAGE_BG = [16, 16, 16];
  const PAD = 16, CAP_H = 20;

  function buildSection(bg) {
    const scenes = [
      buildScenePanel(bg, cells, bgTgaData, bgTgaSize, uiCells),
      buildSceneBarStrip(bg, ringFrameBuf, arcFullBuf, iconCells, uiCells),
      buildSceneRaw2x(bg, uiCells),
    ];
    const rowH = Math.max(...scenes.map((s) => s.h)) + CAP_H;
    const rowW = scenes.reduce((sum, s) => sum + s.w, 0) + PAD * (scenes.length + 1);
    return { scenes, rowW, rowH };
  }

  const sectionBrown = buildSection(BROWN_BG);
  const sectionDark = buildSection(DARK_BG);

  const contentW = Math.max(sectionBrown.rowW, sectionDark.rowW);
  const outW = contentW + 2 * PAD;
  const outH = PAD + sectionBrown.rowH + PAD + sectionDark.rowH + PAD;
  const outBuf = Buffer.alloc(outW * outH * 3);
  for (let i = 0; i < outW * outH; i++) { outBuf[i * 3] = PAGE_BG[0]; outBuf[i * 3 + 1] = PAGE_BG[1]; outBuf[i * 3 + 2] = PAGE_BG[2]; }

  function drawSection(section, bg, gridY) {
    fillRect(outBuf, outW, PAD, gridY, section.rowW, section.rowH, bg);
    let x = PAD + PAD;
    for (const scene of section.scenes) {
      blit(outBuf, outW, outH, scene.canvas, scene.w, scene.h, x, gridY);
      const capY = gridY + Math.max(...section.scenes.map((s) => s.h)) + Math.floor((CAP_H - 14) / 2);
      drawGlyphString(outBuf, outW, outH, DIGITS, x + Math.floor(scene.w / 2) - 3, capY, scene.caption, [255, 255, 255], 2);
      x += scene.w + PAD;
    }
  }
  drawSection(sectionBrown, BROWN_BG, PAD);
  drawSection(sectionDark, DARK_BG, PAD + sectionBrown.rowH + PAD);

  const png = encodePNG_RGB8(outW, outH, outBuf);
  const outPath = path.join(__dirname, "preview_ui.png");
  fs.writeFileSync(outPath, png);
  console.log("wrote " + outPath + " (" + png.length + " bytes, " + outW + "x" + outH + ")");
}

main();
