// TotemBar - tools/preview_ring.js
// Offline preview renderer for the ring flipbook textures: textures/ring_round.tga
// (duration arc / wave / frame band, generated by tools/gen_ring_textures.js),
// textures/ring_fx.tga (glow / hover / pushed / flash cells), and
// textures/ring_pulsearc.tga (Session 76: the pulse-to-next-tick countdown,
// now a second thin circular arc drawn INSIDE the duration arc instead of a
// linear bar under the icon).
// Decodes the raw TGAs, composites a grid of realistic mock scenes the way
// ui.lua does at runtime (icon -> ringTrack/frame band -> ringFill/arc ->
// pulse arc -> pulseWave/wave -> optional fx overlay), and writes
// tools/preview.png so the art can be judged without the WoW client.
//
// Zero dependencies: only Node's built-in "fs", "path", "zlib".
// Run: node tools/preview_ring.js
"use strict";

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

// ---------------------------------------------------------------------
// Texture contract (must match tools/gen_ring_textures.js exactly)
// ---------------------------------------------------------------------
const CELL = 64;         // px per grid cell in ring_round.tga
const GRID_COLS = 8;     // ring_round.tga: 8x8 grid
const ARC_FULL = 61;     // cell index for the "full" duration arc (f = 61/61 = 1.0)
const ARC_95 = 58;       // ~95% arc (58/61 = 95.1%)
const ARC_70 = 43;       // ~70% arc (43/61 = 70.5%)
const ARC_60 = 37;       // cell index for ~60% arc (37/61 = 60.7%)
const ARC_20 = 12;       // cell index for ~20% arc (12/61 = 19.7%)
const WAVE_CELL = 62;    // ripple wave ring
const FRAME_CELL = 63;   // decorative frame band

// ring_pulsearc.tga shares ring_round.tga's exact 64px/8-col cell geometry
// (see tools/gen_ring_textures.js), so it reuses CELL/GRID_COLS above.
const PULSE_40 = 24;     // ~40% pulse arc (24/61 = 39.3%, closest to 40%)

const FX_CELL = 128;     // px per grid cell in ring_fx.tga
const FX_GRID_COLS = 2;  // ring_fx.tga: 2x2 grid
const FX_GLOW = 0;       // "glow" cell
const FX_HOVER = 1;      // "hover" cell
const FX_PUSHED = 2;     // "pushed" cell
const FX_FLASH = 3;      // "flash" cell

// Element tints, copied verbatim from ui.lua's ELEMENT_COLORS table.
const FIRE = [1.00, 0.45, 0.10];
const WATER = [0.25, 0.60, 1.00];
const EARTH = [0.40, 0.85, 0.30];
const WHITE = [1.00, 1.00, 1.00];
const BLACK = [0.00, 0.00, 0.00];

// ---------------------------------------------------------------------
// Scale: real client uses icon=30px, button=36px, ring=48px (see ui.lua's
// BUTTON_SIZE / RING_TEX_SIZE constants). SCALE=2.5 keeps that exact
// 30:36:48 ratio and lands the ring at 120px.
// fx overlays are drawn at their own "screen size" the same way (see the
// rev3 brief's cell-1 comment: 58/64*24 = 21.75px at 48px screen size),
// i.e. sizePxReal * SCALE, same convention as RING_SIZE = 48 * SCALE.
//
// SCENE_SIZE must fit the LARGEST scaled overlay quad, not just the 120px
// ring: the scene-7 wave draws at 120*1.77 = 212.4px (its windowed alpha
// reaches 31/32 of the quad's 106.2px half-width = 102.9px from center),
// and the 64px-screen-size glow reaches 62/64 of 80px = 77.5px. A 140px
// tile (iteration 1) sliced the wave's REAL alpha at the tile boundary and
// produced a rectangular wash in scenes 6/7 - the tile must be >= 2*103px
// so every windowed layer fades to exactly 0 before the blit edge. 220
// gives that plus a small margin.
// ---------------------------------------------------------------------
const SCALE = 2.5;
const ICON_SIZE = 30 * SCALE;   // 75
const RING_SIZE = 48 * SCALE;   // 120
const SCENE_SIZE = 220;         // scene canvas (icon+ring centered; fits the 212px scene-7 wave quad)
const CAP_H = 18;               // caption strip height under each scene
const TILE_W = SCENE_SIZE;
const TILE_H = SCENE_SIZE + CAP_H;
const PAD = 10;                 // padding between tiles / around each grid section

const BROWN_BG = [122, 84, 58];   // "warm mid-brown", like a WoW zone
const DARK_BG = [28, 26, 24];     // dark UI background
const PAGE_BG = [16, 16, 16];     // page backdrop behind both sections

// ===========================================================================
// TGA reader
// ===========================================================================
// Reconstructs a top-down (y=0 = top row) straight-alpha RGBA buffer from the
// 18-byte-header uncompressed truecolor TGA our generator writes (type 2,
// 32bpp, descriptor 0x08 = bottom-up rows + 8 alpha bits). Handles the
// generic bottom-up/top-down descriptor bit so this isn't hard-locked to one
// exact byte value.
function readTGA(filePath) {
  const buf = fs.readFileSync(filePath);
  const idLength = buf[0];
  const imageType = buf[2];
  const width = buf[12] | (buf[13] << 8);
  const height = buf[14] | (buf[15] << 8);
  const bpp = buf[16];
  const descriptor = buf[17];
  if (imageType !== 2) throw new Error("preview_ring: expected uncompressed truecolor TGA (type 2), got " + imageType);
  if (bpp !== 32) throw new Error("preview_ring: expected 32bpp TGA, got " + bpp);

  const bytesPerPixel = bpp / 8;
  const rowBytes = width * bytesPerPixel;
  const dataStart = 18 + idLength; // colorMapType is 0, so no colormap bytes to skip
  const topDown = (descriptor & 0x20) !== 0; // bit 5: 1 = origin top-left, 0 = origin bottom-left

  const data = Buffer.alloc(width * height * 4);
  for (let r = 0; r < height; r++) {
    const rowOffset = dataStart + r * rowBytes;
    const destY = topDown ? r : (height - 1 - r);
    for (let x = 0; x < width; x++) {
      const so = rowOffset + x * bytesPerPixel;
      const b = buf[so], g = buf[so + 1], red = buf[so + 2], a = buf[so + 3];
      const doff = (destY * width + x) * 4;
      data[doff] = red; data[doff + 1] = g; data[doff + 2] = b; data[doff + 3] = a;
    }
  }
  return { width, height, data }; // data: top-down RGBA, straight alpha
}

// Extracts one gridCols-wide cellSize x cellSize grid cell as a
// premultiplied-alpha Float64Array (pr, pg, pb, pa each 0..255, pr/pg/pb
// already scaled by pa/255). Premultiplying before bilinear filtering avoids
// dark fringing at the antialiased edges of the arc/wave/frame/fx shapes
// (their fully-transparent texels are stored as RGBA (0,0,0,0), so naive
// straight-alpha bilinear would pull partially-covered edge pixels toward
// black). Generalized over cellSize/gridCols so it works for both
// ring_round.tga (64px cells, 8 cols) and ring_fx.tga (128px cells, 2 cols).
function extractCellPremultiplied(image, cellIndex, cellSize, gridCols) {
  const col = cellIndex % gridCols;
  const row = Math.floor(cellIndex / gridCols);
  const out = new Float64Array(cellSize * cellSize * 4);
  for (let py = 0; py < cellSize; py++) {
    for (let px = 0; px < cellSize; px++) {
      const sx = col * cellSize + px;
      const sy = row * cellSize + py;
      const so = (sy * image.width + sx) * 4;
      const r = image.data[so], g = image.data[so + 1], b = image.data[so + 2], a = image.data[so + 3];
      const doff = (py * cellSize + px) * 4;
      const af = a / 255;
      out[doff] = r * af;
      out[doff + 1] = g * af;
      out[doff + 2] = b * af;
      out[doff + 3] = a;
    }
  }
  return out;
}

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }
function lerp(a, b, t) { return a + (b - a) * t; }

// Bilinear-samples a premultiplied cellSize x cellSize cell at texel coords
// (sx, sy), clamping to the cell edges. Returns [pr, pg, pb, pa].
function bilinearSample(cellBuf, cellSize, sx, sy) {
  const x0f = Math.floor(sx), y0f = Math.floor(sy);
  const fx = sx - x0f, fy = sy - y0f;
  const x0 = clamp(x0f, 0, cellSize - 1), x1 = clamp(x0f + 1, 0, cellSize - 1);
  const y0 = clamp(y0f, 0, cellSize - 1), y1 = clamp(y0f + 1, 0, cellSize - 1);
  const i00 = (y0 * cellSize + x0) * 4, i10 = (y0 * cellSize + x1) * 4;
  const i01 = (y1 * cellSize + x0) * 4, i11 = (y1 * cellSize + x1) * 4;
  const out = new Array(4);
  for (let c = 0; c < 4; c++) {
    const top = lerp(cellBuf[i00 + c], cellBuf[i10 + c], fx);
    const bot = lerp(cellBuf[i01 + c], cellBuf[i11 + c], fx);
    out[c] = lerp(top, bot, fy);
  }
  return out;
}

// ===========================================================================
// Compositing (straight-RGB canvas, since the final PNG is opaque)
// ===========================================================================
// canvas: Float64Array of size w*h*3 (RGB, 0..255).
// sample: premultiplied [pr, pg, pb, pa] from bilinearSample.
// tint: null to use the sample's own color (frame band / hover's ADD-mode
//   "fx*alpha" literal), or [r,g,b] in 0..1 to recolor a white source
//   texture (arc/wave/fx use pure white + coverage alpha, mirroring
//   ui.lua's SetVertexColor tint-at-runtime).
// alphaMul: extra 0..1 alpha multiplier (wave fade-out, fx intensity).
// mode: "over" (default, standard alpha-over) or "add" (scene 9's hover
//   simulated ADD blend: out = min(255, base + fx*alpha)).
function compositeSample(canvas, idx, sample, tint, alphaMul, mode) {
  const aMul = alphaMul === undefined ? 1 : alphaMul;
  const coverage = sample[3]; // 0..255, equals pr/pg/pb for a pure-white source
  // Guard: where the scaled source is (effectively) transparent, contribute
  // NOTHING - skip before any blending, so bilinear float noise at alpha ~ 0
  // can never tint or wash the destination (alpha < 1/255 is sub-quantum).
  if (coverage < 1) return;
  let r, g, b;
  if (tint) {
    r = coverage * aMul * tint[0];
    g = coverage * aMul * tint[1];
    b = coverage * aMul * tint[2];
  } else {
    r = sample[0] * aMul;
    g = sample[1] * aMul;
    b = sample[2] * aMul;
  }
  if (mode === "add") {
    canvas[idx] = Math.min(255, canvas[idx] + r);
    canvas[idx + 1] = Math.min(255, canvas[idx + 1] + g);
    canvas[idx + 2] = Math.min(255, canvas[idx + 2] + b);
    return;
  }
  const aNorm = (coverage / 255) * aMul;
  const inv = 1 - aNorm;
  canvas[idx] = r + canvas[idx] * inv;
  canvas[idx + 1] = g + canvas[idx + 1] * inv;
  canvas[idx + 2] = b + canvas[idx + 2] * inv;
}

// Composites a texture cell, scaled to layerSize px and centered at (cx,cy)
// in canvas pixel space (continuous coords), straight-alpha "over" (or
// "add" - see compositeSample).
function compositeLayerCentered(canvas, canvasSize, cellBuf, cellSize, cx, cy, layerSize, tint, alphaMul, mode) {
  const half = layerSize / 2;
  const left = cx - half, top = cy - half;
  const x0 = Math.max(0, Math.floor(left));
  const x1 = Math.min(canvasSize - 1, Math.ceil(left + layerSize) - 1);
  const y0 = Math.max(0, Math.floor(top));
  const y1 = Math.min(canvasSize - 1, Math.ceil(top + layerSize) - 1);
  for (let y = y0; y <= y1; y++) {
    const v = (y + 0.5 - top) / layerSize;
    if (v < 0 || v >= 1) continue;
    const sy = v * cellSize - 0.5;
    for (let x = x0; x <= x1; x++) {
      const u = (x + 0.5 - left) / layerSize;
      if (u < 0 || u >= 1) continue;
      const sx = u * cellSize - 0.5;
      const sample = bilinearSample(cellBuf, cellSize, sx, sy);
      compositeSample(canvas, (y * canvasSize + x) * 3, sample, tint, alphaMul, mode);
    }
  }
}

// Procedural fake "spell icon": radial orange->dark gradient + a diagonal
// highlight band, 2x2 supersampled for a smooth band edge. Square, opaque -
// exists so the preview shows how the ring's opaque frame band hides its
// corners.
function iconColorAt(u, v) {
  const dx = u - 0.5, dy = v - 0.5;
  const d = clamp(Math.sqrt(dx * dx + dy * dy) / (Math.SQRT2 * 0.5), 0, 1);
  const orange = [255, 150, 40], dark = [50, 25, 10];
  let r = lerp(orange[0], dark[0], d);
  let g = lerp(orange[1], dark[1], d);
  let b = lerp(orange[2], dark[2], d);
  const diag = u - v; // -1..1, band running top-left to bottom-right
  const dist = Math.abs(diag - 0.15);
  const bandT = clamp(1 - dist / 0.12, 0, 1);
  const band = [255, 235, 180];
  r = lerp(r, band[0], bandT * 0.8);
  g = lerp(g, band[1], bandT * 0.8);
  b = lerp(b, band[2], bandT * 0.8);
  return [r, g, b];
}

function compositeIconSquare(canvas, canvasSize, cx, cy, size, darken) {
  const half = size / 2;
  const left = cx - half, top = cy - half;
  const x0 = Math.max(0, Math.floor(left));
  const x1 = Math.min(canvasSize - 1, Math.ceil(left + size) - 1);
  const y0 = Math.max(0, Math.floor(top));
  const y1 = Math.min(canvasSize - 1, Math.ceil(top + size) - 1);
  const darkFactor = 1 - (darken || 0);
  const SS = 2;
  for (let y = y0; y <= y1; y++) {
    for (let x = x0; x <= x1; x++) {
      const u0 = (x - left) / size, v0 = (y - top) / size;
      if (u0 < 0 || u0 >= 1 || v0 < 0 || v0 >= 1) continue;
      let r = 0, g = 0, b = 0;
      for (let sy = 0; sy < SS; sy++) {
        for (let sx = 0; sx < SS; sx++) {
          const u = (x + (sx + 0.5) / SS - left) / size;
          const v = (y + (sy + 0.5) / SS - top) / size;
          const c = iconColorAt(clamp(u, 0, 1), clamp(v, 0, 1));
          r += c[0]; g += c[1]; b += c[2];
        }
      }
      const n = SS * SS;
      const idx = (y * canvasSize + x) * 3;
      canvas[idx] = (r / n) * darkFactor;
      canvas[idx + 1] = (g / n) * darkFactor;
      canvas[idx + 2] = (b / n) * darkFactor;
    }
  }
}

// ===========================================================================
// Scene rendering
// ===========================================================================
// opts.fx: { cell: FX_GLOW|FX_HOVER|FX_PUSHED|FX_FLASH, sizePxReal (real UI
//   px "screen size", defaults to 48 - the same convention ring_fx cell 1's
//   own doc comment uses), tint (null or [r,g,b] 0..1), alphaMul, mode,
//   under (true = draw BELOW frame/arc/wave, mirroring the in-game
//   BACKGROUND-layer placement of the glow halo; default false = on top) }
// opts.pulseArcIndex/opts.pulseArcTint: cell index into ring_pulsearc.tga
//   (0..61) + [r,g,b] 0..1 tint for the pulse-countdown arc, drawn just
//   after the duration arc - it lives in its own thin radial band strictly
//   inside the duration arc's, so draw order relative to it doesn't matter
//   visually, but it goes before the wave/fx like the other OVERLAY rings.
function renderScene(cells, bgColor, opts) {
  const size = SCENE_SIZE;
  const canvas = new Float64Array(size * size * 3);
  for (let i = 0; i < size * size; i++) {
    canvas[i * 3] = bgColor[0];
    canvas[i * 3 + 1] = bgColor[1];
    canvas[i * 3 + 2] = bgColor[2];
  }
  const cx = size / 2, cy = size / 2;

  // Draw order mirrors ui.lua's texture creation order for a totem button:
  // icon (ARTWORK) -> [fx with under=true, e.g. the glow halo, which sits on
  // the BACKGROUND layer in-game] -> ringTrack/frame (OVERLAY, created
  // first) -> ringFill/arc (OVERLAY, created second, draws over the frame)
  // -> pulseWave/wave (OVERLAY, created last, draws over both) -> fx without
  // under (hover/pushed/flash, drawn last of all).
  function drawFx() {
    const fxBuf = cells.fx(opts.fx.cell);
    const sizePxReal = opts.fx.sizePxReal !== undefined ? opts.fx.sizePxReal : 48;
    const drawSize = sizePxReal * SCALE;
    compositeLayerCentered(canvas, size, fxBuf, FX_CELL, cx, cy, drawSize, opts.fx.tint, opts.fx.alphaMul, opts.fx.mode);
  }
  compositeIconSquare(canvas, size, cx, cy, ICON_SIZE, opts.iconDarken || 0);
  if (opts.fx && opts.fx.under) drawFx();
  compositeLayerCentered(canvas, size, cells.frame, CELL, cx, cy, RING_SIZE, null, 1);
  if (opts.arcIndex !== undefined && opts.arcIndex !== null) {
    compositeLayerCentered(canvas, size, cells.arc(opts.arcIndex), CELL, cx, cy, RING_SIZE, opts.arcTint, 1);
  }
  if (opts.pulseArcIndex !== undefined && opts.pulseArcIndex !== null) {
    compositeLayerCentered(canvas, size, cells.pulseArc(opts.pulseArcIndex), CELL, cx, cy, RING_SIZE, opts.pulseArcTint, 1);
  }
  if (opts.wave) {
    compositeLayerCentered(canvas, size, cells.wave, CELL, cx, cy, RING_SIZE * opts.wave.scale, opts.wave.tint, opts.wave.alpha);
  }
  if (opts.fx && !opts.fx.under) drawFx();
  return canvas;
}

// ---------------------------------------------------------------------
// Tiny 5x7 bitmap digit font, for the "1".."12" scene captions (spec allows
// skipping full labels in favor of simple markers; digits are the minimal
// useful middle ground - identifies each scene without needing a full
// alphabet). Multi-digit captions ("10","11","12") just chain glyphs.
// ---------------------------------------------------------------------
const DIGITS = {
  "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
  "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
  "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
  "3": ["11111", "00010", "00100", "00010", "00001", "10001", "01110"],
  "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
  "5": ["11111", "10000", "11110", "00001", "00001", "10001", "01110"],
  "6": ["00110", "01000", "10000", "11110", "10001", "10001", "01110"],
  "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
  "8": ["01110", "10001", "10001", "01110", "10001", "10001", "01110"],
  "9": ["01110", "10001", "10001", "01111", "00001", "00010", "01100"],
};

function drawDigitString(outBuf, outW, outH, x, y, text, color, scale) {
  let cursorX = x;
  for (let i = 0; i < text.length; i++) {
    const glyph = DIGITS[text[i]];
    if (glyph) {
      for (let gy = 0; gy < 7; gy++) {
        const row = glyph[gy];
        for (let gx = 0; gx < 5; gx++) {
          if (row[gx] === "1") {
            for (let py = 0; py < scale; py++) {
              for (let px = 0; px < scale; px++) {
                const ox = cursorX + gx * scale + px;
                const oy = y + gy * scale + py;
                if (ox < 0 || ox >= outW || oy < 0 || oy >= outH) continue;
                const idx = (oy * outW + ox) * 3;
                outBuf[idx] = color[0]; outBuf[idx + 1] = color[1]; outBuf[idx + 2] = color[2];
              }
            }
          }
        }
      }
    }
    cursorX += (5 + 1) * scale;
  }
  return cursorX - scale; // right edge of last glyph
}

function blit(outBuf, outW, outH, srcCanvas, srcSize, dx, dy) {
  for (let y = 0; y < srcSize; y++) {
    const oy = dy + y;
    if (oy < 0 || oy >= outH) continue;
    for (let x = 0; x < srcSize; x++) {
      const ox = dx + x;
      if (ox < 0 || ox >= outW) continue;
      const si = (y * srcSize + x) * 3;
      const oi = (oy * outW + ox) * 3;
      outBuf[oi] = Math.round(clamp(srcCanvas[si], 0, 255));
      outBuf[oi + 1] = Math.round(clamp(srcCanvas[si + 1], 0, 255));
      outBuf[oi + 2] = Math.round(clamp(srcCanvas[si + 2], 0, 255));
    }
  }
}

function fillRect(outBuf, outW, x0, y0, w, h, color) {
  for (let y = y0; y < y0 + h; y++) {
    for (let x = x0; x < x0 + w; x++) {
      const idx = (y * outW + x) * 3;
      outBuf[idx] = color[0]; outBuf[idx + 1] = color[1]; outBuf[idx + 2] = color[2];
    }
  }
}

// ===========================================================================
// Minimal zero-dependency PNG writer (IHDR + IDAT + IEND, RGB8, filter 0)
// ===========================================================================
const CRC_TABLE = (function () {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buf) {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function pngChunk(type, data) {
  const typeBuf = Buffer.from(type, "ascii");
  const lenBuf = Buffer.alloc(4);
  lenBuf.writeUInt32BE(data.length, 0);
  const crcBuf = Buffer.alloc(4);
  crcBuf.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([lenBuf, typeBuf, data, crcBuf]);
}

function encodePNG_RGB8(width, height, rgbBuffer) {
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;  // bit depth
  ihdr[9] = 2;  // color type: truecolor (RGB)
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace

  const rowBytes = width * 3;
  const raw = Buffer.alloc((rowBytes + 1) * height);
  for (let y = 0; y < height; y++) {
    const rowStart = y * (rowBytes + 1);
    raw[rowStart] = 0; // filter type 0 (None)
    rgbBuffer.copy(raw, rowStart + 1, y * rowBytes, (y + 1) * rowBytes);
  }
  const idatData = zlib.deflateSync(raw);

  return Buffer.concat([
    sig,
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", idatData),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

// ===========================================================================
// Main
// ===========================================================================
function main() {
  const ringPath = path.join(__dirname, "..", "textures", "ring_round.tga");
  const fxPath = path.join(__dirname, "..", "textures", "ring_fx.tga");
  const pulseArcPath = path.join(__dirname, "..", "textures", "ring_pulsearc.tga");
  const ringImage = readTGA(ringPath);
  const fxImage = readTGA(fxPath);
  const pulseArcImage = readTGA(pulseArcPath);

  const frameCellBuf = extractCellPremultiplied(ringImage, FRAME_CELL, CELL, GRID_COLS);
  const waveCellBuf = extractCellPremultiplied(ringImage, WAVE_CELL, CELL, GRID_COLS);
  const arcCache = {};
  function arcCell(idx) {
    if (!arcCache[idx]) arcCache[idx] = extractCellPremultiplied(ringImage, idx, CELL, GRID_COLS);
    return arcCache[idx];
  }
  const pulseArcCache = {};
  function pulseArcCell(idx) {
    if (!pulseArcCache[idx]) pulseArcCache[idx] = extractCellPremultiplied(pulseArcImage, idx, CELL, GRID_COLS);
    return pulseArcCache[idx];
  }
  const fxCache = {};
  function fxCell(idx) {
    if (!fxCache[idx]) fxCache[idx] = extractCellPremultiplied(fxImage, idx, FX_CELL, FX_GRID_COLS);
    return fxCache[idx];
  }
  const cells = { frame: frameCellBuf, wave: waveCellBuf, arc: arcCell, pulseArc: pulseArcCell, fx: fxCell };

  // Scene list (indices 1..12 for captions), per the rev3 brief section E +
  // iteration 2. A few knobs the brief leaves implicit (documented in
  // rev3-art-report.md "deviations"): hover/pushed reuse the full arc for a
  // busier demo scene; pushed/hover/flash fx draw at the "48px screen size"
  // convention from the brief's own cell-1 comment; the annular glow halo
  // (scenes 8/12) draws at 64px screen size UNDER the frame (its in-game
  // home is the background layer, hugging the band from outside); scene
  // 12's wave "30%" is linearly interpolated between the 0%/45% sample
  // points given for scenes 5/6.
  const scenes = [
    { caption: "1", opts: {} },                                                                          // frame only
    { caption: "2", opts: { arcIndex: ARC_FULL, arcTint: FIRE } },                                       // full arc, Fire
    { caption: "3", opts: { arcIndex: ARC_60, arcTint: WATER } },                                        // ~60% arc, Water (caps+comet)
    { caption: "4", opts: { arcIndex: ARC_20, arcTint: EARTH } },                                        // ~20% arc, Earth
    { caption: "5", opts: { arcIndex: ARC_FULL, arcTint: WATER, wave: { scale: 1.0, alpha: 0.85, tint: WATER } } },
    { caption: "6", opts: { arcIndex: ARC_FULL, arcTint: WATER, wave: { scale: 1.4, alpha: 0.47, tint: WATER } } },
    { caption: "7", opts: { arcIndex: ARC_FULL, arcTint: WATER, wave: { scale: 1.77, alpha: 0.13, tint: WATER } } },
    { caption: "8", opts: { arcIndex: ARC_95, arcTint: WATER, fx: { cell: FX_GLOW, sizePxReal: 64, tint: WATER, alphaMul: 0.6, mode: "over", under: true } } },
    { caption: "9", opts: { arcIndex: ARC_FULL, arcTint: FIRE, fx: { cell: FX_HOVER, sizePxReal: 48, tint: null, alphaMul: 1, mode: "add" } } },
    { caption: "10", opts: { arcIndex: ARC_FULL, arcTint: EARTH, fx: { cell: FX_PUSHED, sizePxReal: 48, tint: BLACK, alphaMul: 1, mode: "over" } } },
    { caption: "11", opts: { fx: { cell: FX_FLASH, sizePxReal: 48, tint: WHITE, alphaMul: 0.8, mode: "over" } } },
    { caption: "12", opts: { arcIndex: ARC_70, arcTint: WATER, wave: { scale: 1.27, alpha: 0.6, tint: WATER }, fx: { cell: FX_GLOW, sizePxReal: 64, tint: WHITE, alphaMul: 0.25, mode: "over", under: true } } },
    // 13 "dual arc" - Session 76 ACCEPTANCE SCENE: shadow frame band (now the
    // only look, automatic/default) + duration arc ~70% Fire (outer) + pulse
    // arc ~40% white (inner, own thin radial band) + icon glyph. Rendered on
    // both backgrounds (brown top grid, dark bottom grid) since renderGrid
    // iterates the same scene list for both sections.
    { caption: "13", opts: { arcIndex: ARC_70, arcTint: FIRE, pulseArcIndex: PULSE_40, pulseArcTint: WHITE } },
  ];

  // ---- Layout: top 4x4 grid on brown bg, bottom 13x1 strip on dark bg ----
  // (grown from 4x3/12x1 to fit the new scene 13 "dual arc" - see above)
  const topCols = 4, topRows = 4;
  const topGridW = topCols * TILE_W + (topCols + 1) * PAD;
  const topGridH = topRows * TILE_H + (topRows + 1) * PAD;

  const botCols = 13, botRows = 1;
  const botGridW = botCols * TILE_W + (botCols + 1) * PAD;
  const botGridH = botRows * TILE_H + (botRows + 1) * PAD;

  const MARGIN = 16;
  const SECTION_GAP = 24;
  const contentW = Math.max(topGridW, botGridW);
  const outW = contentW + 2 * MARGIN;
  const outH = MARGIN + topGridH + SECTION_GAP + botGridH + MARGIN;

  const outBuf = Buffer.alloc(outW * outH * 3);
  for (let i = 0; i < outW * outH; i++) {
    outBuf[i * 3] = PAGE_BG[0]; outBuf[i * 3 + 1] = PAGE_BG[1]; outBuf[i * 3 + 2] = PAGE_BG[2];
  }

  function renderGrid(gridX, gridY, cols, rows, bgColor) {
    // Fill the section background (including caption strips) first.
    fillRect(outBuf, outW, gridX, gridY, cols * TILE_W + (cols + 1) * PAD, rows * TILE_H + (rows + 1) * PAD, bgColor);
    for (let i = 0; i < scenes.length && i < cols * rows; i++) {
      const col = i % cols, row = Math.floor(i / cols);
      const tileX = gridX + PAD + col * (TILE_W + PAD);
      const tileY = gridY + PAD + row * (TILE_H + PAD);
      const sceneCanvas = renderScene(cells, bgColor, scenes[i].opts);
      blit(outBuf, outW, outH, sceneCanvas, SCENE_SIZE, tileX, tileY);
      // caption: centered digit(s) under the scene
      const capY = tileY + SCENE_SIZE + Math.floor((CAP_H - 7 * 2) / 2);
      const textW = scenes[i].caption.length * 6 * 2 - 2;
      const capX = tileX + Math.floor((TILE_W - textW) / 2);
      drawDigitString(outBuf, outW, outH, capX, capY, scenes[i].caption, [255, 255, 255], 2);
    }
  }

  const topGridX = MARGIN + Math.floor((contentW - topGridW) / 2);
  const topGridY = MARGIN;
  renderGrid(topGridX, topGridY, topCols, topRows, BROWN_BG);

  const botGridX = MARGIN + Math.floor((contentW - botGridW) / 2);
  const botGridY = topGridY + topGridH + SECTION_GAP;
  renderGrid(botGridX, botGridY, botCols, botRows, DARK_BG);

  const png = encodePNG_RGB8(outW, outH, outBuf);
  const outPath = path.join(__dirname, "preview.png");
  fs.writeFileSync(outPath, png);
  console.log("wrote " + outPath + " (" + png.length + " bytes, " + outW + "x" + outH + ")");
}

main();
